### ISSUE TITLE
Web interface does not work with Safari on a mac

### ISSUE THREAD

**Issue by duelago** [bofh69/AiLight#13]
Buggy.

**Comment by bofh69** [comment]
Does nothing work at all? Does the javascript console say anything? Do you know if AiLight works?

**Comment by duelago** [comment]
No links are working. Can't toggle to the settings page or turn on/off the lamp from Safari. Works perfect in Chrome.

I see this error message in the javascript console:
[Error] SyntaxError: Can't create duplicate variable that shadows a global property: 'colour_lamp'
	(anonymous function)

**Comment by bofh69** [comment]
Seems global variables and html elements can not have the same name in Safari. I've fixed it, but then input[type=color] isn't supported in Safari 11 (at least). I'll try to fix that too before comiting.

**Comment by bofh69** [comment]
It works now.
